from enum import Enum

class DataQualityEnum(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"

class FreshnessEnum(str, Enum):
    FRESH = "FRESH"
    ACCEPTABLE = "ACCEPTABLE"
    AGING = "AGING"
    STALE = "STALE"
    EXPIRED = "EXPIRED"

class ObservationQualityEnum(str, Enum):
    VALID = "VALID"
    SUSPECT = "SUSPECT"
    REJECTED = "REJECTED"
    MISSING = "MISSING"
    STALE = "STALE"

class HazardMeasurementTypeEnum(str, Enum):
    RIVER_WATER_LEVEL = "RIVER_WATER_LEVEL"
    RAINFALL = "RAINFALL"
    RIVER_DISCHARGE = "RIVER_DISCHARGE"
    DAM_LEVEL = "DAM_LEVEL"

class OperationalStatusEnum(str, Enum):
    ACTIVE = "ACTIVE"
    DEGRADED = "DEGRADED"
    OFFLINE = "OFFLINE"
    BLOCKED = "BLOCKED"
    RESTRICTED = "RESTRICTED"
    OPEN = "OPEN"
    LIMITED = "LIMITED"
    CLOSED = "CLOSED"

class StateTypeEnum(str, Enum):
    OBSERVED = "OBSERVED"
    DERIVED = "DERIVED"
    PREDICTED = "PREDICTED"
    SIMULATION = "SIMULATION"

class PriorityClassEnum(str, Enum):
    IMMEDIATE = "IMMEDIATE"
    SHORT_TERM = "SHORT_TERM"
    MEDIUM_TERM = "MEDIUM_TERM"

class ResourceCategoryEnum(str, Enum):
    SHELTER = "SHELTER"
    WATER = "WATER"
    HEALTHCARE = "HEALTHCARE"
    SANITATION = "SANITATION"
    FOOD = "FOOD"
    UTILITIES = "UTILITIES"
    EMERGENCY_SERVICES = "EMERGENCY_SERVICES"

class AllocationStatusEnum(str, Enum):
    RECOMMENDED = "RECOMMENDED"
    ACCEPTED = "ACCEPTED"
    OVERRIDDEN = "OVERRIDDEN"
    REJECTED = "REJECTED"
    UNMET = "UNMET"

class RoleEnum(str, Enum):
    ADMIN = "ADMIN"
    AUTHORITY = "AUTHORITY"
    DATA_OPERATOR = "DATA_OPERATOR"
    VIEWER = "VIEWER"

class JobStatusEnum(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class EvacuationStateEnum(str, Enum):
    # Canonical Normal Lifecycle
    PLANNED = "PLANNED"
    NOTIFIED = "NOTIFIED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    EVACUATION_ORDERED = "EVACUATION_ORDERED"
    MOVING = "MOVING"
    IN_TRANSIT = "IN_TRANSIT"
    ARRIVED = "ARRIVED"
    SHELTERED = "SHELTERED"

    # Operational Exception States (Non-terminal)
    NO_RESPONSE = "NO_RESPONSE"
    ROUTE_BLOCKED = "ROUTE_BLOCKED"
    STUCK = "STUCK"
    REQUIRES_ASSISTANCE = "REQUIRES_ASSISTANCE"

class ResourceStatusEnum(str, Enum):
    NORMAL = "NORMAL"
    CONSTRAINED = "CONSTRAINED"
    EXHAUSTED = "EXHAUSTED"

class SimulationStatusEnum(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class SimulationEventTypeEnum(str, Enum):
    SIMULATION_STARTED = "SIMULATION_STARTED"
    SIMULATION_TICK = "SIMULATION_TICK"
    HAZARD_EXPANDED = "HAZARD_EXPANDED"
    ROAD_BLOCKED = "ROAD_BLOCKED"
    ROAD_REOPENED = "ROAD_REOPENED"
    ROUTE_INVALIDATED = "ROUTE_INVALIDATED"
    ROUTE_REPLANNED = "ROUTE_REPLANNED"
    REROUTE_FAILED = "REROUTE_FAILED"
    EVACUATION_STATE_CHANGED = "EVACUATION_STATE_CHANGED"
    MOVEMENT_PROGRESSED = "MOVEMENT_PROGRESSED"
    ARRIVAL = "ARRIVAL"
    SHELTERED = "SHELTERED"
    REALLOCATION_TRIGGERED = "REALLOCATION_TRIGGERED"
    REALLOCATION_COMPLETED = "REALLOCATION_COMPLETED"
    SIMULATION_PAUSED = "SIMULATION_PAUSED"
    SIMULATION_COMPLETED = "SIMULATION_COMPLETED"
    SIMULATION_FAILED = "SIMULATION_FAILED"
    # Phase A.4 Dynamic Resource Events
    RESOURCE_CONSUMED = "RESOURCE_CONSUMED"
    RESOURCE_WARNING = "RESOURCE_WARNING"
    RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED"
    DESTINATION_CAPACITY_CHANGED = "DESTINATION_CAPACITY_CHANGED"
    DESTINATION_INFEASIBLE = "DESTINATION_INFEASIBLE"
    # Phase A.5 Simulation Control Events
    SIMULATION_RESUMED = "SIMULATION_RESUMED"
    SIMULATION_CANCELLED = "SIMULATION_CANCELLED"




